name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/PickFromFile.sln
    - name: Build
      run: dotnet build src/PickFromFile.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/PickFromFile.sln --no-build --verbosity normal
